// need name of element, image, recipe
// put elements in alphabetical order
export const allRecipes = [
  {
    element1: "",
    element2: "",
    name: "strawberry",
    image: "/strawberry.png",
  },
  {
    element1: "",
    element2: "",
    name: "apple",
    image: "/apple.png",
  },
  {
    element1: "",
    element2: "",
    name: "milk",
    image: "/milk.png",
  },
  {
    element1: "",
    element2: "",
    name: "egg",
    image: "/egg.png",
  },
  {
    element1: "",
    element2: "",
    name: "oil",
    image: "/oil.png",
  },
  {
    element1: "",
    element2: "",
    name: "flour",
    image: "/flour.png",
  },
  {
    element1: "",
    element2: "",
    name: "chocolate",
    image: "/chocolate.png",
  },
  {
    element1: "",
    element2: "",
    name: "lettuce",
    image: "/lettuce.png",
  },
  {
    element1: "",
    element2: "",
    name: "meat",
    image: "/meat.png",
  },
  {
    element1: "",
    element2: "",
    name: "ketchup",
    image: "/ketchup.png",
  },
  {
    element1: "strawberry",
    element2: "strawberry",
    name: "strawberry jam",
    image: "/strawberry_jam.png",
  },
  {
    element1: "flour",
    element2: "strawberry",
    name: "strawberry cake",
    image: "/strawberry_cake.png",
  },
  {
    element1: "flour",
    element2: "flour",
    name: "bread",
    image: "/bread.png",
  },
  {
    element1: "bread",
    element2: "lettuce",
    name: "sandwich",
    image: "/sandwich.png",
  },
  {
    element1: "bread",
    element2: "oil",
    name: "bagel",
    image: "/bagel.png",
  },
  {
    element1: "oil",
    element2: "potato",
    name: "fries",
    image: "/fries.png",
  },
  {
    element1: "egg",
    element2: "oil",
    name: "fried egg",
    image: "/fried_egg.png",
  },
  {
    element1: "egg",
    element2: "flour",
    name: "egg tart",
    image: "/egg_tart.png",
  },
  {
    element1: "egg",
    element2: "egg",
    name: "egg salad",
    image: "/egg_salad.png",
  },
  {
    element1: "chocolate",
    element2: "flour",
    name: "chocolate cake",
    image: "/chocolate_cake.png",
  },
  {
    element1: "cheese",
    element2: "fries",
    name: "nachos",
    image: "/nachos.png",
  },
  {
    element1: "lettuce",
    element2: "nachos",
    name: "taco",
    image: "/taco.png",
  },
  {
    element1: "ketchup",
    element2: "meat",
    name: "meatball",
    image: "/meatball.png",
  },
  {
    element1: "flour",
    element2: "meatball",
    name: "spaghetti",
    image: "/spaghetti.png",
  },
  {
    element1: "bread",
    element2: "meat",
    name: "burger",
    image: "/burger.png",
  },
  {
    element1: "apple",
    element2: "flour",
    name: "apple pie",
    image: "/apple_pie.png",
  },
  {
    element1: "cheese",
    element2: "flour",
    name: "cheesecake",
    image: "/cheesecake.png",
  },
  {
    element1: "bagel",
    element2: "chocolate",
    name: "donut",
    image: "/donut.png",
  },
  {
    element1: "chocolate",
    element2: "milk",
    name: "ice cream",
    image: "/ice_cream.png",
  },
  {
    element1: "bread",
    element2: "ketchup",
    name: "pizza",
    image: "/pizza.png",
  },
  {
    element1: "bread",
    element2: "jam",
    name: "jam bread",
    image: "/jam_bread.png",
  },
  {
    element1: "milk",
    element2: "milk",
    name: "cheese",
    image: "/cheese.png",
  },
  {
    element1: "bread",
    element2: "ice cream",
    name: "waffle",
    image: "/waffle.png",
  },
];
